name: Download workflow artifact
description: Download and extract the latest artifact from a workflow
author: MeaWallet
branding:
  icon: download
  color: orange
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{github.token}}
  repo:
    description: Repository name with owner (like meallet/meapay-pin-sdk)
    required: true
  workflow:
    description: Workflow name
    required: true
  branch:
    description: Branch name
    required: true
  name:
    description: Artifact to download
    required: false
  path:
    description: Where to unpack the artifact
    required: false
    default: "./"
outputs:
  error_message:
    description: The error message, if an error occurs
runs:
  using: node16
  main: main.js
